### ISSUE TITLE
server failed to start

### ISSUE THREAD

**Issue by wackoamd1** [Fourmisain/IndyPets#3]
server failed to start with the latest version 0.8.0
0.7.1 worked perfectly

<html>
<body>
<div class="row-fluid" style="width: 1540px; color: rgb(85, 85, 85); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console span12 widget dark" style="float: left; min-height: 30px; margin-left: 0px; width: 1540px; position: relative; margin-bottom: -1px; border-top: 1px solid rgb(85, 85, 85); border-right: 1px solid rgb(85, 85, 85); border-bottom: none; border-left: 1px solid rgb(85, 85, 85); border-image: initial; border-radius: 2px; background-color: rgb(252, 252, 252); box-shadow: none; display: block; box-sizing: border-box;"><section class="body" style="display: block; border-radius: 0px 0px 2px 2px;"><div class="body-inner console-inner no-padding" sticky-console="" style="height: 65vh; overflow-y: scroll; font-family: monospace; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); padding: 0px !important; border-top: none;">

[13:06:34] ain/FATAL]: Failed to start the minecraft server
--
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'indypets'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class me.shedaniel.autoconfig.gui.registry.api.GuiProvider in environment type SERVER
at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at com.lizin5ths.indypets.IndyPets.onInitialize(IndyPets.java:16) ~[indypets-0.8.0.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
... 15 more

</div></section></div></div><div class="row-fluid" style="width: 1540px; color: rgb(85, 85, 85); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="body-inner"><div class="control-group" style="margin-bottom: 10px;"><div class="controls console-input ng-scope" ng-repeat="obj in user_input" style="border-right: 1px solid; border-bottom: 1px solid; border-left: 1px solid; border-image: initial; border-top: none; background-color: rgb(0, 0, 0);"><label style="cursor: pointer; font-size: 12px; font-weight: 400; line-height: 20px; display: block; margin-bottom: 5px; color: rgb(255, 255, 255); position: absolute; padding: 0.45em 0.6em; background-color: rgb(0, 0, 0); text-align: right;">&gt;</label></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Fourmisain** [comment]
Oops, the GUI stuff goes in the client initializer!
Fixed in 0.8.1.
